name: netguru_values
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dartz: ^0.9.1
  equatable: ^1.2.5
  flutter_bloc: ^6.0.5
  get_it: ^5.0.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true
